import type { Product } from "./types";

export const MOCK_PRODUCTS: Product[] = [
  // ── Sữa rửa mặt ──────────────────────────────────────────────────────────
  {
    id: "prod-01",
    slug: "sua-rua-mat-bot-ceramide",
    name: "Sữa Rửa Mặt Tạo Bọt Nhẹ Dịu Ceramide",
    brand: "GlowScan",
    price: 350_000,
    image: "https://picsum.photos/seed/gs-c01/800/800",
    category: "Sữa rửa mặt",
    stock: 24,
    ingredients: ["Ceramide NP", "Panthenol", "Allantoin", "Glycerin"],
    concerns: ["Khô da", "Kết cấu da"],
    routineSlot: "Bước 1 — Sáng & Tối",
    rating: 4.8,
    reviewCount: 142,
    description:
      "Sữa rửa mặt tạo bọt nhẹ nhàng, cân bằng pH, loại bỏ bụi bẩn mà không làm mất đi hàng rào bảo vệ của da. Ceramide và panthenol giúp da sạch thoáng nhưng vẫn dịu ẩm sau mỗi lần rửa.",
    isBestSeller: true,
  },
  {
    id: "prod-02",
    slug: "sap-tay-trang-cleansing-balm",
    name: "Sáp Tẩy Trang Làm Tan Chảy Bụi Bẩn",
    brand: "GlowScan",
    price: 280_000,
    image: "https://picsum.photos/seed/gs-c02/800/800",
    category: "Sữa rửa mặt",
    stock: 22,
    ingredients: [
      "Squalane",
      "Caprylic/Capric Triglyceride",
      "Jojoba Oil",
      "Vitamin E",
    ],
    concerns: ["Khô da", "Kết cấu da"],
    routineSlot: "Bước 1 — Chỉ dùng tối, làm sạch lần 1",
    rating: 4.8,
    reviewCount: 97,
    description:
      "Sáp tẩy trang dạng oil-to-milk tan chảy hoàn toàn kem chống nắng và makeup. Da sạch hoàn toàn, không nhờn, sẵn sàng cho bước làm sạch tiếp theo.",
  },
  {
    id: "prod-03",
    slug: "gel-rua-mat-salicylic-acid",
    name: "Gel Rửa Mặt Kiểm Soát Nhờn Salicylic Acid",
    brand: "GlowScan",
    price: 295_000,
    image: "https://picsum.photos/seed/gs-c03/800/800",
    category: "Sữa rửa mặt",
    stock: 18,
    ingredients: [
      "Salicylic Acid 0.5%",
      "Tea Tree Extract",
      "Niacinamide",
      "Zinc PCA",
    ],
    concerns: ["Mụn", "Kết cấu da"],
    routineSlot: "Bước 1 — Sáng & Tối",
    rating: 4.6,
    reviewCount: 88,
    description:
      "Gel rửa mặt chứa Salicylic Acid nhẹ nhàng thông thoáng lỗ chân lông và kiểm soát dầu thừa, phù hợp cho da dầu mụn sử dụng hàng ngày.",
  },
  {
    id: "prod-04",
    slug: "sua-rua-mat-hyaluronic-acid",
    name: "Sữa Rửa Mặt Dưỡng Ẩm Hyaluronic Acid",
    brand: "GlowScan",
    price: 320_000,
    image: "https://picsum.photos/seed/gs-c04/800/800",
    category: "Sữa rửa mặt",
    stock: 30,
    ingredients: ["Hyaluronic Acid", "Aloe Vera", "Panthenol", "Glycerin"],
    concerns: ["Khô da"],
    routineSlot: "Bước 1 — Sáng & Tối",
    rating: 4.7,
    reviewCount: 115,
    description:
      "Sữa rửa mặt kết hợp Hyaluronic Acid giúp làm sạch nhẹ nhàng trong khi bổ sung độ ẩm, lý tưởng cho da khô và da thường.",
    isNew: true,
  },
  {
    id: "prod-05",
    slug: "foam-rua-mat-than-hoat-tinh",
    name: "Foam Rửa Mặt Làm Sạch Sâu Than Hoạt Tính",
    brand: "GlowScan",
    price: 265_000,
    image: "https://picsum.photos/seed/gs-c05/800/800",
    category: "Sữa rửa mặt",
    stock: 15,
    ingredients: [
      "Activated Charcoal",
      "Kaolin Clay",
      "Tea Tree Oil",
      "Aloe Vera",
    ],
    concerns: ["Mụn", "Kết cấu da"],
    routineSlot: "Bước 1 — Tối",
    rating: 4.4,
    reviewCount: 67,
    description:
      "Foam rửa mặt với than hoạt tính hút sạch bụi bẩn, dầu thừa ẩn sâu trong lỗ chân lông, cho da thông thoáng và sạch mịn.",
  },
  {
    id: "prod-06",
    slug: "gel-rua-mat-da-nhay-cam",
    name: "Gel Rửa Mặt Dịu Nhẹ Cho Da Nhạy Cảm",
    brand: "GlowScan",
    price: 310_000,
    image: "https://picsum.photos/seed/gs-c06/800/800",
    category: "Sữa rửa mặt",
    stock: 20,
    ingredients: ["Centella Asiatica", "Oat Extract", "Allantoin", "Glycerin"],
    concerns: ["Khô da"],
    routineSlot: "Bước 1 — Sáng & Tối",
    rating: 4.9,
    reviewCount: 201,
    description:
      "Gel rửa mặt không xà phòng, pH 5.5, dịu nhẹ tuyệt đối cho da nhạy cảm, da bị kích ứng hay da đang dùng retinol.",
    isBestSeller: true,
  },
  {
    id: "prod-07",
    slug: "dau-tay-trang-jojoba",
    name: "Dầu Tẩy Trang Làm Sạch Kép Jojoba",
    brand: "GlowScan",
    price: 345_000,
    image: "https://picsum.photos/seed/gs-c07/800/800",
    category: "Sữa rửa mặt",
    stock: 12,
    ingredients: ["Jojoba Oil", "Rosehip Oil", "Vitamin E", "Squalane"],
    concerns: ["Khô da", "Kết cấu da"],
    routineSlot: "Bước 1 — Tối, làm sạch lần 1",
    rating: 4.7,
    reviewCount: 79,
    description:
      "Dầu tẩy trang dạng lỏng nhẹ nhàng hoà tan makeup, kem chống nắng và bụi bẩn mà không làm mất độ ẩm tự nhiên của da.",
  },
  {
    id: "prod-08",
    slug: "mousse-rua-mat-lua-mach",
    name: "Mousse Rửa Mặt Sáng Da Chiết Xuất Lúa Mạch",
    brand: "GlowScan",
    price: 285_000,
    image: "https://picsum.photos/seed/gs-c08/800/800",
    category: "Sữa rửa mặt",
    stock: 27,
    ingredients: ["Barley Extract", "Vitamin B5", "Niacinamide 2%", "Glycerin"],
    concerns: ["Xỉn màu", "Kết cấu da"],
    routineSlot: "Bước 1 — Sáng & Tối",
    rating: 4.5,
    reviewCount: 54,
    description:
      "Mousse rửa mặt mịn mượt từ chiết xuất lúa mạch và Niacinamide nhẹ nhàng làm sáng da qua từng lần rửa mặt.",
    isNew: true,
  },

  // ── Serum trị liệu ────────────────────────────────────────────────────────
  {
    id: "prod-09",
    slug: "tinh-chat-niacinamide-10",
    name: "Tinh Chất Niacinamide 10% Se Khít Lỗ Chân Lông",
    brand: "GlowScan",
    price: 420_000,
    image: "https://picsum.photos/seed/gs-s01/800/800",
    category: "Serum trị liệu",
    stock: 3,
    ingredients: [
      "Niacinamide 10%",
      "Zinc PCA 1%",
      "Hyaluronic Acid",
      "Allantoin",
    ],
    concerns: ["Mụn", "Kết cấu da", "Xỉn màu"],
    routineSlot: "Bước 3 — Sáng & Tối, sau toner",
    rating: 4.9,
    reviewCount: 287,
    description:
      "Công thức Niacinamide và Zinc nồng độ cao giúp se khít lỗ chân lông, giảm mụn và cân bằng dầu nhờn để da trông sáng mịn hơn.",
    isBestSeller: true,
  },
  {
    id: "prod-10",
    slug: "tinh-chat-retinol-03",
    name: "Tinh Chất Retinol 0.3% Phục Hồi Da Ban Đêm",
    brand: "GlowScan",
    price: 680_000,
    image: "https://picsum.photos/seed/gs-s02/800/800",
    category: "Serum trị liệu",
    stock: 15,
    ingredients: ["Retinol 0.3%", "Squalane", "Vitamin E", "Peptides"],
    concerns: ["Kết cấu da", "Xỉn màu", "Mụn"],
    routineSlot: "Bước 3 — Chỉ dùng tối, 2–3 lần/tuần",
    rating: 4.7,
    reviewCount: 134,
    description:
      "Serum retinol dịu nhẹ thúc đẩy tái tạo tế bào, làm mờ nếp nhăn và cải thiện kết cấu da tổng thể qua đêm mà không gây kích ứng.",
  },
  {
    id: "prod-11",
    slug: "tinh-chat-peptide-nang-co",
    name: "Tinh Chất Peptide Chống Lão Hoá Nâng Cơ",
    brand: "GlowScan",
    price: 750_000,
    image: "https://picsum.photos/seed/gs-s03/800/800",
    category: "Serum trị liệu",
    stock: 10,
    ingredients: [
      "Matrixyl 3000",
      "Argireline",
      "Hyaluronic Acid",
      "Vitamin C",
    ],
    concerns: ["Kết cấu da", "Xỉn màu"],
    routineSlot: "Bước 3 — Sáng & Tối",
    rating: 4.6,
    reviewCount: 98,
    description:
      "Cocktail peptide thế hệ mới kích thích sản sinh collagen, giảm nhăn và nâng cơ mặt từ bên trong theo thời gian.",
    isNew: true,
  },
  {
    id: "prod-12",
    slug: "tinh-chat-azelaic-acid-10",
    name: "Tinh Chất Azelaic Acid 10% Trị Nám & Mụn",
    brand: "GlowScan",
    price: 490_000,
    image: "https://picsum.photos/seed/gs-s04/800/800",
    category: "Serum trị liệu",
    stock: 14,
    ingredients: [
      "Azelaic Acid 10%",
      "Niacinamide 4%",
      "Panthenol",
      "Allantoin",
    ],
    concerns: ["Mụn", "Xỉn màu"],
    routineSlot: "Bước 3 — Sáng & Tối",
    rating: 4.5,
    reviewCount: 76,
    description:
      "Azelaic Acid đa năng vừa trị mụn, vừa mờ nám và vết thâm sau mụn, đồng thời dịu nhẹ cho da kích ứng.",
  },
  {
    id: "prod-13",
    slug: "tinh-chat-bha-2",
    name: "Tinh Chất BHA 2% Thông Thoáng Lỗ Chân Lông",
    brand: "GlowScan",
    price: 380_000,
    image: "https://picsum.photos/seed/gs-s05/800/800",
    category: "Serum trị liệu",
    stock: 19,
    ingredients: ["Salicylic Acid 2%", "Green Tea Extract", "Hyaluronic Acid"],
    concerns: ["Mụn", "Kết cấu da"],
    routineSlot: "Bước 3 — Tối",
    rating: 4.7,
    reviewCount: 163,
    description:
      "Serum BHA tan trong dầu thấm sâu vào lỗ chân lông, làm sạch bã nhờn và tế bào chết ẩn sâu, giảm mụn đầu đen hiệu quả.",
    isBestSeller: true,
  },
  {
    id: "prod-14",
    slug: "tinh-chat-hyaluronic-acid",
    name: "Tinh Chất Hyaluronic Acid Cấp Ẩm Sâu Tức Thì",
    brand: "GlowScan",
    price: 360_000,
    image: "https://picsum.photos/seed/gs-s06/800/800",
    category: "Serum trị liệu",
    stock: 35,
    ingredients: [
      "Hyaluronic Acid 3 trọng lượng phân tử",
      "Panthenol",
      "Allantoin",
    ],
    concerns: ["Khô da"],
    routineSlot: "Bước 2 — Sáng & Tối, sau toner",
    rating: 4.8,
    reviewCount: 245,
    description:
      "Ba trọng lượng phân tử HA kết hợp cấp ẩm đa tầng từ bề mặt đến sâu trong da, cho da căng mọng và mịn màng ngay sau lần dùng đầu.",
  },
  {
    id: "prod-15",
    slug: "tinh-chat-alpha-arbutin-2",
    name: "Tinh Chất Alpha Arbutin 2% Mờ Vết Thâm",
    brand: "GlowScan",
    price: 410_000,
    image: "https://picsum.photos/seed/gs-s07/800/800",
    category: "Serum trị liệu",
    stock: 16,
    ingredients: [
      "Alpha Arbutin 2%",
      "Hyaluronic Acid",
      "Kojic Acid",
      "Niacinamide",
    ],
    concerns: ["Xỉn màu", "Mụn"],
    routineSlot: "Bước 3 — Sáng & Tối",
    rating: 4.6,
    reviewCount: 119,
    description:
      "Alpha Arbutin ức chế sản sinh melanin hiệu quả, mờ vết thâm sau mụn và đốm nâu, cho tông da đều hơn theo tuần.",
  },
  {
    id: "prod-16",
    slug: "tinh-chat-cica-centella",
    name: "Tinh Chất Cica Centella Phục Hồi Da Kích Ứng",
    brand: "GlowScan",
    price: 435_000,
    image: "https://picsum.photos/seed/gs-s08/800/800",
    category: "Serum trị liệu",
    stock: 21,
    ingredients: [
      "Centella Asiatica 50%",
      "Madecassoside",
      "Asiaticoside",
      "Panthenol",
    ],
    concerns: ["Khô da", "Kết cấu da"],
    routineSlot: "Bước 3 — Sáng & Tối",
    rating: 4.9,
    reviewCount: 312,
    description:
      "Serum Cica nồng độ cao phục hồi hàng rào bảo vệ da, giảm đỏ và kích ứng tức thì, lý tưởng sau khi lăn kim hoặc peel da.",
    isBestSeller: true,
  },
  {
    id: "prod-17",
    slug: "tinh-chat-egf-tai-tao",
    name: "Tinh Chất EGF Tái Tạo Tế Bào Da Chuyên Sâu",
    brand: "GlowScan",
    price: 820_000,
    image: "https://picsum.photos/seed/gs-s09/800/800",
    category: "Serum trị liệu",
    stock: 7,
    ingredients: [
      "EGF (Epidermal Growth Factor)",
      "Peptide Complex",
      "Hyaluronic Acid",
    ],
    concerns: ["Kết cấu da", "Xỉn màu"],
    routineSlot: "Bước 3 — Tối",
    rating: 4.7,
    reviewCount: 58,
    description:
      "EGF kích thích tái tạo tế bào da cấp độ phân tử, cải thiện nếp nhăn, sẹo và tổng thể kết cấu da sau liệu trình 4 tuần.",
    isNew: true,
  },
  {
    id: "prod-18",
    slug: "tinh-chat-bakuchiol-1",
    name: "Tinh Chất Bakuchiol 1% Thay Thế Retinol",
    brand: "GlowScan",
    price: 560_000,
    image: "https://picsum.photos/seed/gs-s10/800/800",
    category: "Serum trị liệu",
    stock: 13,
    ingredients: ["Bakuchiol 1%", "Sea Buckthorn", "Rosehip Oil", "Vitamin E"],
    concerns: ["Kết cấu da", "Xỉn màu", "Khô da"],
    routineSlot: "Bước 3 — Tối",
    rating: 4.5,
    reviewCount: 87,
    description:
      "Chiết xuất thực vật Bakuchiol mang lại hiệu quả tương tự retinol nhưng dịu nhẹ hơn nhiều, phù hợp cho da nhạy cảm không chịu được retinol.",
  },

  // ── Serum dưỡng sáng ──────────────────────────────────────────────────────
  {
    id: "prod-19",
    slug: "tinh-chat-vitamin-c-15",
    name: "Tinh Chất Vitamin C 15% Dưỡng Sáng & Mờ Thâm",
    brand: "GlowScan",
    price: 580_000,
    image: "https://picsum.photos/seed/gs-b01/800/800",
    category: "Serum dưỡng sáng",
    stock: 12,
    ingredients: [
      "Ascorbic Acid 15%",
      "Ferulic Acid",
      "Vitamin E",
      "Hyaluronic Acid",
    ],
    concerns: ["Xỉn màu", "Kết cấu da"],
    routineSlot: "Bước 3 — Chỉ dùng sáng, trước kem chống nắng",
    rating: 4.7,
    reviewCount: 198,
    description:
      "Serum Vitamin C ổn định làm sáng đều màu da, mờ đốm thâm và cung cấp khả năng chống oxy hóa trước các tác nhân môi trường hàng ngày.",
    isNew: true,
  },
  {
    id: "prod-20",
    slug: "tinh-chat-glutathione",
    name: "Tinh Chất Glutathione Dưỡng Trắng Sáng Da",
    brand: "GlowScan",
    price: 620_000,
    image: "https://picsum.photos/seed/gs-b02/800/800",
    category: "Serum dưỡng sáng",
    stock: 9,
    ingredients: [
      "Glutathione",
      "Vitamin C 5%",
      "Niacinamide",
      "Tranexamic Acid",
    ],
    concerns: ["Xỉn màu"],
    routineSlot: "Bước 3 — Tối",
    rating: 4.6,
    reviewCount: 143,
    description:
      "Glutathione kết hợp Vitamin C và Tranexamic Acid tạo nên bộ tứ dưỡng sáng mạnh mẽ, giảm melanin toàn diện cho da trắng sáng đều màu.",
  },
  {
    id: "prod-21",
    slug: "tinh-chat-tranexamic-acid",
    name: "Tinh Chất Tranexamic Acid Mờ Nám Đều Màu",
    brand: "GlowScan",
    price: 510_000,
    image: "https://picsum.photos/seed/gs-b03/800/800",
    category: "Serum dưỡng sáng",
    stock: 17,
    ingredients: [
      "Tranexamic Acid 3%",
      "Niacinamide 5%",
      "Alpha Arbutin",
      "Kojic Acid",
    ],
    concerns: ["Xỉn màu", "Kết cấu da"],
    routineSlot: "Bước 3 — Sáng & Tối",
    rating: 4.8,
    reviewCount: 176,
    description:
      "Tranexamic Acid liều cao ức chế hình thành nám từ gốc rễ, kết hợp Niacinamide và Alpha Arbutin để đều màu da toàn diện.",
  },
  {
    id: "prod-22",
    slug: "tinh-chat-vitamin-c-20-ferulic",
    name: "Tinh Chất Vitamin C 20% + Vitamin E & Ferulic",
    brand: "GlowScan",
    price: 695_000,
    image: "https://picsum.photos/seed/gs-b04/800/800",
    category: "Serum dưỡng sáng",
    stock: 6,
    ingredients: ["Ascorbic Acid 20%", "Vitamin E 1%", "Ferulic Acid 0.5%"],
    concerns: ["Xỉn màu"],
    routineSlot: "Bước 3 — Chỉ dùng sáng",
    rating: 4.9,
    reviewCount: 221,
    description:
      "Công thức CE Ferulic cổ điển hiệu quả vượt trội — Vitamin C 20% bền vững nhờ Vitamin E và Ferulic Acid ổn định, cho kết quả dưỡng sáng rõ rệt nhất.",
    isBestSeller: true,
  },
  {
    id: "prod-23",
    slug: "tinh-chat-kojic-acid-2",
    name: "Tinh Chất Kojic Acid 2% Làm Sáng Da",
    brand: "GlowScan",
    price: 390_000,
    image: "https://picsum.photos/seed/gs-b05/800/800",
    category: "Serum dưỡng sáng",
    stock: 22,
    ingredients: ["Kojic Acid 2%", "Vitamin C 5%", "Niacinamide", "Glycerin"],
    concerns: ["Xỉn màu", "Mụn"],
    routineSlot: "Bước 3 — Tối",
    rating: 4.4,
    reviewCount: 92,
    description:
      "Kojic Acid chiết xuất tự nhiên từ nấm lên men ức chế tyrosinase, mờ vết thâm và đều màu da nhẹ nhàng không kích ứng.",
  },
  {
    id: "prod-24",
    slug: "serum-duong-sang-cam-quyt",
    name: "Serum Dưỡng Sáng Chiết Xuất Cam Quýt",
    brand: "GlowScan",
    price: 445_000,
    image: "https://picsum.photos/seed/gs-b06/800/800",
    category: "Serum dưỡng sáng",
    stock: 28,
    ingredients: [
      "Citrus Extract",
      "Vitamin C 8%",
      "Licorice Root",
      "Hyaluronic Acid",
    ],
    concerns: ["Xỉn màu", "Kết cấu da"],
    routineSlot: "Bước 3 — Sáng & Tối",
    rating: 4.5,
    reviewCount: 108,
    description:
      "Chiết xuất cam quýt tươi mát giàu Vitamin C tự nhiên kết hợp Licorice Root làm sáng da dịu nhẹ, hương thơm dễ chịu.",
    isNew: true,
  },
  {
    id: "prod-25",
    slug: "tinh-chat-lactic-acid-10",
    name: "Tinh Chất Lactic Acid 10% Tẩy Da Chết & Sáng",
    brand: "GlowScan",
    price: 420_000,
    image: "https://picsum.photos/seed/gs-b07/800/800",
    category: "Serum dưỡng sáng",
    stock: 19,
    ingredients: [
      "Lactic Acid 10%",
      "Hyaluronic Acid",
      "Tasmanian Pepperberry",
    ],
    concerns: ["Xỉn màu", "Kết cấu da", "Khô da"],
    routineSlot: "Bước 3 — Tối",
    rating: 4.6,
    reviewCount: 131,
    description:
      "Lactic Acid AHA nhẹ nhàng tẩy tế bào chết và dưỡng sáng đồng thời, kích thước phân tử lớn hơn Glycolic Acid nên ít kích ứng hơn.",
  },

  // ── Tẩy tế bào chết ──────────────────────────────────────────────────────
  {
    id: "prod-26",
    slug: "nuoc-tay-da-chet-aha-bha",
    name: "Nước Tẩy Da Chết AHA 7% + BHA 1%",
    brand: "GlowScan",
    price: 390_000,
    image: "https://picsum.photos/seed/gs-e01/800/800",
    category: "Tẩy tế bào chết",
    stock: 18,
    ingredients: [
      "Glycolic Acid 5%",
      "Lactic Acid 2%",
      "Salicylic Acid 1%",
      "Aloe Vera",
    ],
    concerns: ["Kết cấu da", "Mụn", "Xỉn màu"],
    routineSlot: "Bước 2 — Chỉ dùng tối, 2–3 lần/tuần",
    rating: 4.6,
    reviewCount: 165,
    description:
      "Tẩy da chết dạng leave-on kết hợp AHA và BHA nhẹ nhàng làm mịn kết cấu da, thông thoáng lỗ chân lông và lộ ra làn da sáng mướt hơn.",
  },
  {
    id: "prod-27",
    slug: "tay-da-chet-hat-gao-nhat",
    name: "Tẩy Da Chết Vật Lý Hạt Gạo Nhật Bản",
    brand: "GlowScan",
    price: 260_000,
    image: "https://picsum.photos/seed/gs-e02/800/800",
    category: "Tẩy tế bào chết",
    stock: 25,
    ingredients: [
      "Rice Bran Powder",
      "Rice Extract",
      "Niacinamide",
      "Glycerin",
    ],
    concerns: ["Xỉn màu", "Kết cấu da"],
    routineSlot: "Bước 1 — Tối, 2 lần/tuần",
    rating: 4.5,
    reviewCount: 84,
    description:
      "Hạt gạo Nhật mịn nhẹ làm sạch tế bào chết vật lý, tinh chất gạo bảo vệ hàng rào bảo vệ da và dưỡng sáng tự nhiên.",
  },
  {
    id: "prod-28",
    slug: "peeling-gel-te-bao-chet",
    name: "Peeling Gel Tẩy Tế Bào Chết Nhẹ Nhàng",
    brand: "GlowScan",
    price: 315_000,
    image: "https://picsum.photos/seed/gs-e03/800/800",
    category: "Tẩy tế bào chết",
    stock: 16,
    ingredients: [
      "Cellulose",
      "Papain Enzyme",
      "Aloe Vera",
      "Centella Asiatica",
    ],
    concerns: ["Kết cấu da", "Mụn"],
    routineSlot: "Bước 1 — Tối, 1–2 lần/tuần",
    rating: 4.4,
    reviewCount: 72,
    description:
      "Peeling gel enzyme nhẹ nhàng vo trôi tế bào chết chỉ bằng cách massage, không cần scrub hạt — phù hợp cho da nhạy cảm.",
    isNew: true,
  },
  {
    id: "prod-29",
    slug: "tay-da-chet-pha-da-nhay-cam",
    name: "Tẩy Da Chết Hóa Học PHA Cho Da Nhạy Cảm",
    brand: "GlowScan",
    price: 375_000,
    image: "https://picsum.photos/seed/gs-e04/800/800",
    category: "Tẩy tế bào chết",
    stock: 14,
    ingredients: [
      "Gluconolactone 5%",
      "Lactobionic Acid 3%",
      "Panthenol",
      "Aloe Vera",
    ],
    concerns: ["Kết cấu da", "Khô da"],
    routineSlot: "Bước 2 — Tối",
    rating: 4.7,
    reviewCount: 96,
    description:
      "PHA phân tử lớn tẩy tế bào chết rất dịu nhẹ, vừa tẩy da chết vừa dưỡng ẩm đồng thời — lựa chọn hàng đầu cho da nhạy cảm và da khô.",
  },
  {
    id: "prod-30",
    slug: "tay-da-chet-moi-mat-ong",
    name: "Tẩy Da Chết Môi Đường Mật Ong",
    brand: "GlowScan",
    price: 185_000,
    image: "https://picsum.photos/seed/gs-e05/800/800",
    category: "Tẩy tế bào chết",
    stock: 40,
    ingredients: ["Honey", "Brown Sugar", "Vitamin E", "Jojoba Oil"],
    concerns: ["Khô da", "Kết cấu da"],
    routineSlot: "Dùng khi cần, 2–3 lần/tuần",
    rating: 4.6,
    reviewCount: 189,
    description:
      "Tẩy da chết môi từ đường nâu và mật ong tự nhiên, làm mềm và căng mọng môi tức thì, hương ngọt ngào dễ chịu.",
    isBestSeller: true,
  },
  {
    id: "prod-31",
    slug: "scrub-muoi-hong-himalaya",
    name: "Scrub Tẩy Tế Bào Chết Muối Hồng Himalaya",
    brand: "GlowScan",
    price: 295_000,
    image: "https://picsum.photos/seed/gs-e06/800/800",
    category: "Tẩy tế bào chết",
    stock: 20,
    ingredients: [
      "Himalayan Pink Salt",
      "Coconut Oil",
      "Lavender Oil",
      "Vitamin E",
    ],
    concerns: ["Kết cấu da", "Khô da"],
    routineSlot: "Bước 1 — Tối, 1 lần/tuần",
    rating: 4.3,
    reviewCount: 61,
    description:
      "Muối hồng Himalaya kết hợp dầu dừa tẩy tế bào chết và dưỡng ẩm toàn thân, da mềm mịn sau mỗi lần tắm.",
  },

  // ── Kem dưỡng ẩm ─────────────────────────────────────────────────────────
  {
    id: "prod-32",
    slug: "kem-duong-phuc-hoi-ceramide",
    name: "Kem Dưỡng Phục Hồi Hàng Rào Da Ceramide",
    brand: "GlowScan",
    price: 460_000,
    image: "https://picsum.photos/seed/gs-m01/800/800",
    category: "Kem dưỡng ẩm",
    stock: 31,
    ingredients: [
      "Ceramide NP",
      "Ceramide AP",
      "Cholesterol",
      "Fatty Acids",
      "Squalane",
    ],
    concerns: ["Khô da"],
    routineSlot: "Bước 4 — Sáng & Tối, bước cuối cùng",
    rating: 4.9,
    reviewCount: 321,
    description:
      "Kem dưỡng đặc nhưng không nhờn, bổ sung lipid tự nhiên tái tạo hàng rào bảo vệ da. Lý tưởng cho da nhạy cảm, khô hoặc hàng rào bảo vệ bị tổn thương.",
    isBestSeller: true,
  },
  {
    id: "prod-33",
    slug: "kem-duong-am-gel-hyaluronic",
    name: "Kem Dưỡng Ẩm Nhẹ Dạng Gel Hyaluronic Acid",
    brand: "GlowScan",
    price: 380_000,
    image: "https://picsum.photos/seed/gs-m02/800/800",
    category: "Kem dưỡng ẩm",
    stock: 28,
    ingredients: [
      "Hyaluronic Acid",
      "Aloe Vera",
      "Niacinamide 3%",
      "Panthenol",
    ],
    concerns: ["Khô da", "Mụn"],
    routineSlot: "Bước 4 — Sáng & Tối",
    rating: 4.7,
    reviewCount: 178,
    description:
      "Gel dưỡng ẩm nhẹ như nước, thấm nhanh không bóng nhờn, phù hợp cho da dầu mụn cần dưỡng ẩm mà không làm bít lỗ chân lông.",
  },
  {
    id: "prod-34",
    slug: "kem-duong-am-shea-squalane",
    name: "Kem Dưỡng Ẩm Sâu Shea Butter & Squalane",
    brand: "GlowScan",
    price: 495_000,
    image: "https://picsum.photos/seed/gs-m03/800/800",
    category: "Kem dưỡng ẩm",
    stock: 20,
    ingredients: ["Shea Butter", "Squalane", "Ceramide", "Fatty Acids"],
    concerns: ["Khô da"],
    routineSlot: "Bước 4 — Tối",
    rating: 4.8,
    reviewCount: 142,
    description:
      "Kem dưỡng giàu dưỡng chất từ Shea Butter và Squalane, nuôi dưỡng da khô cực độ và phục hồi hàng rào bảo vệ sau đêm dài.",
  },
  {
    id: "prod-35",
    slug: "kem-duong-da-dau-mun",
    name: "Kem Dưỡng Dạng Sữa Nhẹ Cho Da Dầu Mụn",
    brand: "GlowScan",
    price: 340_000,
    image: "https://picsum.photos/seed/gs-m04/800/800",
    category: "Kem dưỡng ẩm",
    stock: 33,
    ingredients: [
      "Niacinamide 5%",
      "Zinc PCA",
      "Salicylic Acid 0.3%",
      "Aloe Vera",
    ],
    concerns: ["Mụn", "Kết cấu da"],
    routineSlot: "Bước 4 — Sáng & Tối",
    rating: 4.6,
    reviewCount: 157,
    description:
      "Sữa dưỡng ẩm không gây mụn với Niacinamide và Zinc kiểm soát nhờn, cung cấp độ ẩm vừa đủ cho da dầu mụn.",
  },
  {
    id: "prod-36",
    slug: "kem-mat-chong-quang-tham-peptide",
    name: "Kem Mắt Chống Quầng Thâm & Nếp Nhăn Peptide",
    brand: "GlowScan",
    price: 520_000,
    image: "https://picsum.photos/seed/gs-m05/800/800",
    category: "Kem dưỡng ẩm",
    stock: 11,
    ingredients: ["Matrixyl 3000", "Caffeine", "Vitamin K", "Hyaluronic Acid"],
    concerns: ["Xỉn màu", "Kết cấu da"],
    routineSlot: "Bước 4 — Sáng & Tối",
    rating: 4.5,
    reviewCount: 93,
    description:
      "Kem mắt peptide chuyên biệt giảm quầng thâm nhờ Caffeine và Vitamin K, đồng thời lấp đầy nếp nhăn vùng mắt bằng Matrixyl.",
    isNew: true,
  },
  {
    id: "prod-37",
    slug: "kem-duong-ban-dem-phuc-hoi",
    name: "Kem Dưỡng Ban Đêm Phục Hồi & Tái Tạo Da",
    brand: "GlowScan",
    price: 580_000,
    image: "https://picsum.photos/seed/gs-m06/800/800",
    category: "Kem dưỡng ẩm",
    stock: 14,
    ingredients: [
      "Retinyl Palmitate",
      "Peptide Complex",
      "Ceramide",
      "Rosehip Oil",
    ],
    concerns: ["Kết cấu da", "Xỉn màu", "Khô da"],
    routineSlot: "Bước 4 — Chỉ dùng tối",
    rating: 4.7,
    reviewCount: 124,
    description:
      "Kem đêm giàu dưỡng chất kết hợp retinyl palmitate nhẹ nhàng, peptide và ceramide cùng nhau tái tạo da tối đa trong giấc ngủ.",
  },
  {
    id: "prod-38",
    slug: "kem-duong-toan-than-shea",
    name: "Kem Dưỡng Ẩm Toàn Thân Shea Butter",
    brand: "GlowScan",
    price: 380_000,
    image: "https://picsum.photos/seed/gs-m07/800/800",
    category: "Kem dưỡng ẩm",
    stock: 45,
    ingredients: ["Shea Butter", "Cocoa Butter", "Vitamin E", "Almond Oil"],
    concerns: ["Khô da", "Kết cấu da"],
    routineSlot: "Sau tắm hàng ngày",
    rating: 4.8,
    reviewCount: 267,
    description:
      "Kem dưỡng toàn thân đặc sệt từ Shea và Cocoa Butter, khoá ẩm 24 giờ, da mềm mịn mượt như nhung sau mỗi lần dùng.",
    isBestSeller: true,
  },
  {
    id: "prod-39",
    slug: "kem-duong-collagen-chong-lao-hoa",
    name: "Kem Dưỡng Collagen Chống Lão Hoá",
    brand: "GlowScan",
    price: 650_000,
    image: "https://picsum.photos/seed/gs-m08/800/800",
    category: "Kem dưỡng ẩm",
    stock: 9,
    ingredients: [
      "Hydrolyzed Collagen",
      "CoQ10",
      "Vitamin C",
      "Peptide Complex",
    ],
    concerns: ["Kết cấu da", "Xỉn màu"],
    routineSlot: "Bước 4 — Sáng & Tối",
    rating: 4.5,
    reviewCount: 76,
    description:
      "Collagen thuỷ phân cộng với CoQ10 chống oxy hoá tác động hiệp đồng làm đầy nếp nhăn và cải thiện độ đàn hồi da theo thời gian.",
  },
  {
    id: "prod-40",
    slug: "kem-duong-am-avene-da-nhay",
    name: "Kem Dưỡng Ẩm Chuyên Biệt Vùng Cổ & Ngực",
    brand: "GlowScan",
    price: 430_000,
    image: "https://picsum.photos/seed/gs-m09/800/800",
    category: "Kem dưỡng ẩm",
    stock: 18,
    ingredients: [
      "Caffeine",
      "Peptide Complex",
      "Hyaluronic Acid",
      "Vitamin C",
    ],
    concerns: ["Kết cấu da", "Xỉn màu"],
    routineSlot: "Sáng & Tối, sau kem mặt",
    rating: 4.4,
    reviewCount: 52,
    description:
      "Kem dưỡng chuyên cho vùng cổ và ngực thường bị bỏ qua, kết hợp peptide và caffeine căng da và giảm nhăn vùng décolleté.",
    isNew: true,
  },

  // ── Kem chống nắng ────────────────────────────────────────────────────────
  {
    id: "prod-41",
    slug: "kem-chong-nang-spf50-pa4",
    name: "Kem Chống Nắng Bảo Vệ Toàn Diện SPF 50+ PA++++",
    brand: "GlowScan",
    price: 320_000,
    image: "https://picsum.photos/seed/gs-n01/800/800",
    category: "Kem chống nắng",
    stock: 8,
    ingredients: [
      "Zinc Oxide 10%",
      "Tinosorb S",
      "Uvinul A Plus",
      "Niacinamide 3%",
    ],
    concerns: ["Xỉn màu"],
    routineSlot: "Bước 5 — Chỉ dùng sáng, bước cuối cùng",
    rating: 4.8,
    reviewCount: 243,
    description:
      "Kem chống nắng khoáng vật lai phổ rộng, lớp phủ mỏng nhẹ. Niacinamide 3% giúp duy trì tông da đều trong suốt cả ngày.",
    isNew: true,
  },
  {
    id: "prod-42",
    slug: "kem-chong-nang-vat-ly-da-nhay",
    name: "Kem Chống Nắng Vật Lý Dành Cho Da Nhạy Cảm SPF 50",
    brand: "GlowScan",
    price: 345_000,
    image: "https://picsum.photos/seed/gs-n02/800/800",
    category: "Kem chống nắng",
    stock: 22,
    ingredients: [
      "Zinc Oxide 18%",
      "Titanium Dioxide 5%",
      "Centella Asiatica",
      "Aloe Vera",
    ],
    concerns: ["Khô da", "Xỉn màu"],
    routineSlot: "Bước 5 — Sáng",
    rating: 4.7,
    reviewCount: 189,
    description:
      "Chống nắng vật lý 100% khoáng chất, không gây kích ứng, không có hoá chất lọc tia UV — lựa chọn an toàn cho da nhạy cảm và da đang trị liệu.",
    isBestSeller: true,
  },
  {
    id: "prod-43",
    slug: "gel-chong-nang-kiem-soat-nhon",
    name: "Gel Chống Nắng Kiểm Soát Nhờn SPF 50+ PA++++",
    brand: "GlowScan",
    price: 295_000,
    image: "https://picsum.photos/seed/gs-n03/800/800",
    category: "Kem chống nắng",
    stock: 30,
    ingredients: ["Tinosorb S", "Uvinul A Plus", "Niacinamide 5%", "Silica"],
    concerns: ["Mụn", "Kết cấu da"],
    routineSlot: "Bước 5 — Sáng",
    rating: 4.8,
    reviewCount: 312,
    description:
      "Gel chống nắng siêu nhẹ kiểm soát nhờn suốt ngày dài nhờ Silica, SPF 50+ PA++++ bảo vệ toàn diện mà không gây bít lỗ chân lông.",
    isBestSeller: true,
  },
  {
    id: "prod-44",
    slug: "kem-chong-nang-duong-am-spf30",
    name: "Kem Chống Nắng Dưỡng Ẩm SPF 30 Cho Da Khô",
    brand: "GlowScan",
    price: 310_000,
    image: "https://picsum.photos/seed/gs-n04/800/800",
    category: "Kem chống nắng",
    stock: 17,
    ingredients: [
      "Zinc Oxide 8%",
      "Hyaluronic Acid",
      "Shea Butter",
      "Vitamin E",
    ],
    concerns: ["Khô da"],
    routineSlot: "Bước 5 — Sáng",
    rating: 4.6,
    reviewCount: 134,
    description:
      "Kem chống nắng vừa bảo vệ vừa dưỡng ẩm sâu nhờ Hyaluronic Acid và Shea Butter, lý tưởng cho da khô trong mùa khô.",
  },
  {
    id: "prod-45",
    slug: "kem-chong-nang-tone-up",
    name: "Kem Chống Nắng Tone Up Dưỡng Sáng SPF 50+",
    brand: "GlowScan",
    price: 365_000,
    image: "https://picsum.photos/seed/gs-n05/800/800",
    category: "Kem chống nắng",
    stock: 26,
    ingredients: [
      "Tinosorb M",
      "Pearl Extract",
      "Niacinamide 4%",
      "Hyaluronic Acid",
    ],
    concerns: ["Xỉn màu"],
    routineSlot: "Bước 5 — Sáng",
    rating: 4.7,
    reviewCount: 198,
    description:
      "Kem chống nắng tone-up nâng sáng tức thì, cho lớp base tự nhiên như không makeup kèm bảo vệ SPF 50+ PA++++ toàn diện.",
  },
  {
    id: "prod-46",
    slug: "xit-chong-nang-tien-dung",
    name: "Xịt Chống Nắng Tiện Dụng SPF 50+ PA++++",
    brand: "GlowScan",
    price: 285_000,
    image: "https://picsum.photos/seed/gs-n06/800/800",
    category: "Kem chống nắng",
    stock: 34,
    ingredients: ["Uvinul A Plus", "Tinosorb S", "Panthenol", "Aloe Vera"],
    concerns: ["Xỉn màu"],
    routineSlot: "Xịt lại mỗi 2 giờ khi ra ngoài",
    rating: 4.5,
    reviewCount: 176,
    description:
      "Dạng xịt tiện lợi để bổ sung chống nắng qua lớp makeup, phân tử mịn bay đều, không làm ố vàng hay trôi makeup.",
  },
  {
    id: "prod-47",
    slug: "kem-chong-nang-vung-mat",
    name: "Kem Chống Nắng Vùng Quanh Mắt SPF 40",
    brand: "GlowScan",
    price: 340_000,
    image: "https://picsum.photos/seed/gs-n07/800/800",
    category: "Kem chống nắng",
    stock: 12,
    ingredients: ["Zinc Oxide 12%", "Caffeine", "Vitamin K", "Peptide Complex"],
    concerns: ["Xỉn màu", "Kết cấu da"],
    routineSlot: "Bước 5 — Sáng",
    rating: 4.4,
    reviewCount: 67,
    description:
      "Kem chống nắng nhẹ dịu cho vùng quanh mắt mỏng manh, không gây cay xốt mắt, kết hợp Caffeine giảm phù nề và quầng thâm.",
    isNew: true,
  },
  {
    id: "prod-48",
    slug: "kem-chong-nang-toan-than-chong-nuoc",
    name: "Kem Chống Nắng Toàn Thân Chống Nước SPF 50+",
    brand: "GlowScan",
    price: 375_000,
    image: "https://picsum.photos/seed/gs-n08/800/800",
    category: "Kem chống nắng",
    stock: 20,
    ingredients: ["Avobenzone", "Homosalate", "Vitamin E", "Aloe Vera"],
    concerns: ["Xỉn màu"],
    routineSlot: "Bôi toàn thân 15 phút trước khi ra ngoài",
    rating: 4.6,
    reviewCount: 143,
    description:
      "Kem chống nắng toàn thân chống nước 80 phút, bảo vệ khi bơi và hoạt động ngoài trời, không nhờn, không trắng da.",
  },
  {
    id: "prod-49",
    slug: "cushion-chong-nang-spf50",
    name: "Cushion Chống Nắng Dưỡng Ẩm SPF 50+ PA++++",
    brand: "GlowScan",
    price: 420_000,
    image: "https://picsum.photos/seed/gs-n09/800/800",
    category: "Kem chống nắng",
    stock: 15,
    ingredients: [
      "Titanium Dioxide",
      "Hyaluronic Acid",
      "Niacinamide",
      "Pearl Extract",
    ],
    concerns: ["Xỉn màu", "Khô da"],
    routineSlot: "Bước 5 — Sáng, bổ sung qua ngày",
    rating: 4.7,
    reviewCount: 221,
    description:
      "Cushion chống nắng SPF 50+ PA++++ kết hợp coverage nhẹ, dưỡng ẩm và tone up — bổ sung chống nắng qua ngày tiện lợi không làm dày lớp nền.",
  },
  {
    id: "prod-50",
    slug: "kem-chong-nang-tre-em-diu-nhe",
    name: "Kem Chống Nắng Trẻ Em Dịu Nhẹ SPF 50+",
    brand: "GlowScan",
    price: 295_000,
    image: "https://picsum.photos/seed/gs-n10/800/800",
    category: "Kem chống nắng",
    stock: 38,
    ingredients: [
      "Zinc Oxide 20%",
      "Aloe Vera",
      "Chamomile Extract",
      "Panthenol",
    ],
    concerns: ["Khô da"],
    routineSlot: "Bôi toàn thân 15 phút trước khi ra ngoài",
    rating: 4.9,
    reviewCount: 178,
    description:
      "Kem chống nắng vật lý 100% an toàn cho da trẻ em và da nhạy cảm nhất, không hương liệu, không paraben, được kiểm định da liễu.",
    isBestSeller: true,
  },
];
